### ISSUE TITLE
Thinking bigger

### ISSUE THREAD

**Issue by ianks** [fitzgen/winliner#3]
First of all, incredible work here.

My question is a more philosophical one - since `winliner` provides a strong foundation for WASM PGO, would it make sense to think of it as a home for future PGO optimizations (rather than limiting it to indirect call inlining)? 

There’s a number of PGO ideas I’ve wanted to try out, and a convenient starting point with all of the plumbing set up would help a ton!

I know it’s a very new project, so maybe I’m putting the cart before the horse here. But food for thought, at least.

**Comment by fitzgen** [comment]
This project won't be in a state to evolve in that direction for quite a while, but I could imagine it doing that one day. In the meantime, feel free to fork and try out your ideas.
